### PR TITLE
tests: use npm ci

### PR DESCRIPTION
**Pull request by DanielRuf**
`npm ci` is much faster and is meant for CI. This PR is meant for evaluating the new ci command and testig the performance and compare the logs of Travis CI.

https://docs.npmjs.com/cli/ci
http://blog.npmjs.org/post/171556855892/introducing-npm-ci-for-faster-more-reliable

### CODE REVIEW

**Comment by feross** [comment]
Thanks for the PR, but I don't really want to complicate things here for no reason. If it's not too inconvenient, could you test this on another repo?

I prefer to minimize the travis configuration as much as possible and I also don't use package-lock.json for packages (it's meant for apps, not packages).

Cheers.

**Comment by DanielRuf** [comment]
package-lovk.json should be always committed afaik.

I'll further evaluate and ask the Travis team when we get `npm ci`.

**Comment by feross** [comment]
There's no point to committing `package-lock.json` inside packages because it cannot be published to npm:

> One key detail about package-lock.json is that it cannot be published, and it will be ignored if found in any place other than the toplevel package

It's for top-level apps, not for packages. If you use it inside a package it will only confuse you when you run `npm install` and get different (locked) dependencies than your users will get.

**Comment by DanielRuf** [comment]
Sure, this PR was purely meant for evaluating the results anyway snd just for the faster CI builds.

> It's for top-level apps, not for packages.

Not in general, I also work on (big) projects and there it is not uncommon to commit it. Also dev / CI !== build =)

**Comment by DanielRuf** [comment]
Also see https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/, things have also changed since npm 5.

**Comment by feross** [comment]
Neither of those links disproves my claim that `package-lock.json` is counter-productive when used in a package that is meant to be depended-upon by other packages.

I'm not interested in continuing this debate here.

**Pull request closed without merging**
