### PR TITLE
Sync organizations with data from BackYourStack

### PR DESCRIPTION
**Pull request by znarf**
Last update: 2019-03-26.

Script used:
https://github.com/opencollective/backyourstack/blob/master/src/scripts/update-thanks-organizations.js

The data set can be seen there:
https://github.com/opencollective/backyourstack/blob/master/src/data/projects.json

### CODE REVIEW

**Comment by feross** [comment]
Hey @znarf, do you mind re-running the script and resending this PR?

**Comment by znarf** [comment]
@feross pleasure to do that.

**Comment by znarf** [comment]
@feross PR updated.

**Comment by feross** [comment]
Thanks for the pull request! You're awesome! 🤩

giphy

**Pull request merged**
