### PR TITLE
add @tunnckoCore / @olstenlarck to authors

### PR DESCRIPTION
**Pull request by olstenlarck**
And if you accept these packages that I added, would be great. They are pretty old, stable and just most used by many and starred. Won't add more.

Thanks. :100:

### CODE REVIEW

**Comment by feross** [comment]
Hey, thanks for the PR! Is there any reason you added the packages directly to the list? That's usually only necessary for team projects.

It seems like all the packages you added to the list have `tunnckocore` as an author. So you could just do this:

```js
const authors = {
  olstenlarck: 'https://www.paypal.me/tunnckoCore',
  tunnckocore: 'https://www.paypal.me/tunnckoCore'
}
```

Then any package with either `olstenlarck` or `tunnckocore` as a maintainer will be detected.

**Comment by olstenlarck** [comment]
There is no more `tunnckocore` _user_ on npm, converted it to org, which in turn was worst mistake in my life :laughing: :dagger: 

Hm. Yea, make sense, now got it. Will remove the packages.

**Comment by feross** [comment]
Oh, interesting. Okay, I'll update this PR and merge

**Comment by olstenlarck** [comment]
Great, thanks :100:

**Pull request merged**
